//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_P1_Grupo02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PAV_PARCIAL_IEntities : DbContext
    {
        public PAV_PARCIAL_IEntities()
            : base("name=PAV_PARCIAL_IEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<TIENDAS> TIENDAS { get; set; }
        public virtual DbSet<PERSONAS> PERSONAS { get; set; }
    }
}
