//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_P1_Grupo02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public int ID_PERSONA { get; set; }
        public string IDENTIFICACION { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public int EDAD { get; set; }
        public string ESTADO { get; set; }
    }
}
